name: Proto-commerce Pipeline

on: 
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Cypress Tests
        run: yarn test
    
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
            path: cypress/reports/html/index.html
      
      - name: Send Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "📥 *<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here to download the Cypress HTML Report>*"
            }    
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
